In [2]:
import numpy as np

In [8]:
x =[[1,2],[3,4]]
total = 0
for i in x:
    total += sum(i)
print(total)

TypeError: 'int' object is not callable

In [9]:
del sum

In [10]:
x =[[1,2],[3,4]]
total = 0
for i in x:
    total += sum(i)
print(total)

10


In [11]:
x = [[1,2],[3,4]]
nx = np.array(x)

In [14]:
print(nx.sum())
print(nx.min())
print(nx.max())
print(nx.std())
print(nx.var())
print(nx.mean())

10
1
4
1.118033988749895
1.25
2.5


In [15]:
type(nx)

numpy.ndarray

In [17]:
print(nx.shape)  # shape of matrix
print(nx.size)  # total elements
print(nx.dtype) # type of elements


(2, 2)
4
int64


In [18]:
y = [[1,2,3],[4,5,6],[7,8,9]]


functions to create matrix
- `arange`: create a range of numbers
- `linspace`: create a matrix of specified number of elements
- `ones`: create a matrix of ones
- `zeros`: create a matrix of zeros
- `random.rand`: create a matrix of random floats
- `random.randint`: create a matrix of random integers
- `diag`: create a matrix of diagonal elements

In [20]:
a = np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [21]:
np.arange(1, 3, .2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [24]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.zeros((1,3), dtype = int)

array([[0, 0, 0]])

In [33]:
np.random.randint(1, 100, 10)

array([15, 50, 79, 59, 79,  7, 43, 81, 81, 63], dtype=int32)

In [34]:
np.random.randint(-4, 7, (4,3))

array([[-1,  3, -3],
       [ 2,  5, -3],
       [ 4,  6,  0],
       [ 1,  0, -3]], dtype=int32)

In [35]:
np.random.randint(-4, 7, (4,3,2))

array([[[ 2,  0],
        [ 3, -2],
        [ 4, -1]],

       [[ 5,  5],
        [-3,  3],
        [ 1, -2]],

       [[ 0,  3],
        [ 0,  4],
        [ 6,  5]],

       [[ 4, -2],
        [-1,  3],
        [-1,  2]]], dtype=int32)

In [36]:
np.random.rand(5)

array([0.92936928, 0.79842928, 0.40865604, 0.76188168, 0.88677609])

In [38]:
np.random.rand(10,5)

array([[0.70353167, 0.9845152 , 0.5449545 , 0.99235831, 0.21259628],
       [0.91997466, 0.2787328 , 0.15211503, 0.91344736, 0.52462409],
       [0.53787247, 0.29404129, 0.61259217, 0.82247782, 0.4499474 ],
       [0.26060515, 0.43821983, 0.47434469, 0.66873737, 0.99033529],
       [0.01089415, 0.20426984, 0.89598221, 0.99314603, 0.56551416],
       [0.45355536, 0.11278909, 0.63669713, 0.43297222, 0.12013289],
       [0.11041613, 0.69838641, 0.91484193, 0.5233454 , 0.01082758],
       [0.26972339, 0.66508288, 0.63083822, 0.27960963, 0.06695246],
       [0.29112295, 0.94655552, 0.95787489, 0.68181943, 0.31967128],
       [0.7877398 , 0.25895772, 0.17979833, 0.6029573 , 0.94666306]])

In [39]:
np.set_printoptions(precision=3)
np.random.rand(10,5)

array([[0.414, 0.916, 0.554, 0.494, 0.893],
       [0.279, 0.671, 0.914, 0.915, 0.502],
       [0.659, 0.389, 0.448, 0.602, 0.158],
       [0.707, 0.39 , 0.145, 0.005, 0.019],
       [0.46 , 0.666, 0.213, 0.502, 0.815],
       [0.972, 0.308, 0.996, 0.193, 0.264],
       [0.367, 0.555, 0.495, 0.027, 0.924],
       [0.847, 0.803, 0.373, 0.666, 0.959],
       [0.611, 0.609, 0.828, 0.567, 0.175],
       [0.878, 0.746, 0.364, 0.58 , 0.018]])

In [40]:
x =[1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [44]:
#reshape
np.arange(10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
x= np.linspace(1, 5, 25).reshape(5,5)

In [49]:
x.flatten()

array([1.   , 1.167, 1.333, 1.5  , 1.667, 1.833, 2.   , 2.167, 2.333,
       2.5  , 2.667, 2.833, 3.   , 3.167, 3.333, 3.5  , 3.667, 3.833,
       4.   , 4.167, 4.333, 4.5  , 4.667, 4.833, 5.   ])

In [50]:
y = np.arange(1, 26).reshape(5,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [51]:
y.transpose()

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [52]:
y.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

MATHS

In [53]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

[[6 6 8]
 [3 8 4]
 [8 5 5]]
[[3 9 2]
 [8 4 2]
 [5 9 6]]


In [54]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 9 15 10]
 [11 12  6]
 [13 14 11]]
[[ 3 -3  6]
 [-5  4  2]
 [ 3 -4 -1]]
[[18 54 16]
 [24 32  8]
 [40 45 30]]
[[2.    0.667 4.   ]
 [0.375 2.    2.   ]
 [1.6   0.556 0.833]]


In [55]:
a.dot(b)  # dot product

array([[106, 150,  72],
       [ 93,  95,  46],
       [ 89, 137,  56]], dtype=int32)

In [56]:
a + 10

array([[16, 16, 18],
       [13, 18, 14],
       [18, 15, 15]], dtype=int32)

Stats

In [57]:
print(a.mean())

5.888888888888889


In [60]:
print(a.mean())
print(a.mean(axis=0)) # column wise
print(a.mean(axis=1)) # row wise


5.888888888888889
[5.667 6.333 5.667]
[6.667 5.    6.   ]


In [61]:
print(a.sum())
print(a.sum(axis=0)) # column wise
print(a.sum(axis=1)) # row wise


53
[17 19 17]
[20 15 18]


In [62]:
np.sin(a)

array([[-0.279, -0.279,  0.989],
       [ 0.141,  0.989, -0.757],
       [ 0.989, -0.959, -0.959]])

In [70]:
print(np.cos(a))


[[ 0.96   0.96  -0.146]
 [-0.99  -0.146 -0.654]
 [-0.146  0.284  0.284]]


In [ ]:
print(np.exp(a))
print(np.max(a))
print(np.min(a))

In [65]:
x = np.random.randint(1, 100, (2,5))
print(x)

[[11 15 10 32 14]
 [ 3 44  2 47 55]]


In [67]:
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())


55
9
2
7


- slicing
    - 1D -[start:stop:step]
    - 2D -[row_start:row_stop:row_step]

In [3]:
x= np.arange(1,11)
print(x[:5])
print(x[-5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [4]:
x= np.linspace(1, 100, 25).reshape(5,5).astype(int)
print(x)
print(x[0])    # row index 0
print(x[-1])   # last row 
print(x[2])    # # row index2
print(x[:3])  # row index 0 to 2
print(x[-2])  #  last 2 rows

print(x[:0]) # coulmn index 0
print(x[:,-1]) # last coulmn

[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1  5  9 13 17]
[ 83  87  91  95 100]
[42 46 50 54 58]
[[ 1  5  9 13 17]
 [21 25 29 34 38]
 [42 46 50 54 58]]
[62 67 71 75 79]
[]
[ 17  38  58  79 100]


filtering

In [9]:
x>50  # boolean filter

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [10]:
x[x>50]   # broadcasting

array([ 54,  58,  62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [11]:
x[(x>40) & (x<80)]

array([42, 46, 50, 54, 58, 62, 67, 71, 75, 79])

In [12]:
x[x % 2 == 0]

array([ 34,  38,  42,  46,  50,  54,  58,  62, 100])

3rd party libraries

`plotly` - interactive plot using html

`matplotlib` - ploting library for almost all types of plots(image)

`seaborn` - plotting library for statistical plots(extension of mat)

`scipy` - for support in  seaborn

`nbformat` - for support in plotly

`statsmodels` - fpr support in seaborn